### ISSUE TITLE
CAMH

### ISSUE THREAD

**Issue by kimdesmond** [rrsg2020/data_submission#10]
**Name**: (Sofia Chavez, Kim Desmond)

**Number of datasets (sets of inversion recovery measurements**: (1)

Submission Checklist:

* [ ] Have you collected all the raw data exported directly from scanner into a single folder?
* [ ] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [ ] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by mathieuboudreau** [comment]
Hi @kimdesmond,

Did you ever acquire a dataset for this submission?

**Comment by mathieuboudreau** [comment]
Since this issue has become stale (I've never heard back from the authors), I'm going to close this issue for now. If ever @kimdesmond you want to continue your submission, please just respond to this GitHub issue or send me an email, and I'll re-open this issue.

Best,

Mathieu

**Comment by kimdesmond** [comment]
Hi Mathieu,  I had responded through email.. I will re-post it here: 
"We didn't get a chance before the lockdown, unfortunately!  We have some datasets in healthy subjects using similar inversion times and TR, but nothing that matches the challenge protocol exactly.   If we are able to scan volunteers before ISMRM we will submit something then, if possible. "

**Comment by mathieuboudreau** [comment]
Hi Kim,

Sorry about that - I just double checked and can't find any record that I received that email, it must have gotten caught by my spam filter or something. Thanks for the response - the door will always be open for you to complete your submission if you can and are willing!

Thanks!

Mathieu

**Comment by mathieuboudreau** [comment]
Hi @kimdesmond ,

Sorry about that - I just double checked and can't find any record that I received that email, it must have gotten caught by my spam filter or something. Thanks for the response - the door will always be open for you to complete your submission if you can and are willing!

Thanks!

Mathieu

**Comment by kimdesmond** [comment]
My first response was to the original email, and it may have gone to 
"notifications@github.com" instead of to rrsg2020 specifically.  The 
second time I responded through the website, which worked... and this 
time I am using "reply-all" which includes a unique-looking address so 
it should reach you.

- Kim
