### ISSUE TITLE
Data ready for review

### ISSUE THREAD

**Issue by ghost** [rrsg2020/data_submission#11]
**Name**: Matthew Grech-Sollars

**Number of datasets (sets of inversion recovery measurements**: 1

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by mathieuboudreau** [comment]
Hi @mattgs1,

Thank you for submitting a well-formatted dataset! Only minor syntax changes were needed in the configuration files.

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/67b8p/

I tested your dataset using both magnitude-only and magntidue+phase, and they ran succesfully.

# Magnitude fit

Pipeline output:

<img width="557" alt="Capture d’écran 2020-02-25 à 13 52 43" src="https://user-images.githubusercontent.com/1421029/75271033-2266c600-57d6-11ea-89eb-5d59c1a57151.png">


Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_11?filepath=data_submission%2Ft1_fitting_magnitude.ipynb)

# Complex fit

Pipeline output:

<img width="557" alt="Capture d’écran 2020-02-25 à 13 58 35" src="https://user-images.githubusercontent.com/1421029/75271542-eed86b80-57d6-11ea-9f4a-79ea3a7ee809.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_11?filepath=data_submission%2Ft1_fitting_complex.ipynb)

Thank you for your submission!
