### ISSUE TITLE
Center for Mind/Brain Sciences (CIMeC), University of Trento, Italy

### ISSUE THREAD

**Issue by JorgeJovicich** [rrsg2020/data_submission#12]
**Name**: Stefano Tambalo, Jorge Jovicich

**Number of datasets (sets of inversion recovery measurements**: 4

Submission Checklist:

* [yes ] Have you collected all the raw data exported directly from scanner into a single folder?
* [yes ] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [yes ] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by JorgeJovicich** [comment]
Data sharing link submitted to rrsg.challenge@gmail.com

**Comment by mathieuboudreau** [comment]
Hi @JorgeJovicich,

Thank you for submitting a well-formatted dataset! Only minor syntax changes were needed in the configuration files.

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/t9wv5/

I tested your subject_1 dataset using both your 20 channel and 64 channel datasets, and they ran successfully.

# 20 Channel Coil

Pipeline output:

<img width="557" alt="Capture d’écran 2020-02-25 à 18 05 53" src="https://user-images.githubusercontent.com/1421029/75290206-7b485580-57fa-11ea-8cb0-a40ba20dcc94.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_12?filepath=data_submission%2Ft1_fitting_20ch.ipynb)

# 64 Channel Coil

Pipeline output:

<img width="557" alt="Capture d’écran 2020-02-25 à 17 53 44" src="https://user-images.githubusercontent.com/1421029/75290216-7edbdc80-57fa-11ea-938f-2b931632d37f.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_12?filepath=data_submission%2Ft1_fitting_64ch.ipynb)

Thank you for your submission!

**Comment by mathieuboudreau** [comment]
Hello @JorgeJovicich ,

As you are the designated person listed for your dataset, the challenge organizers sent you an email (email listed in your submission (jorge.jovicich(AT)unitn.it) last July (subject: "2020 ISMRM T1 mapping challenge data consent"), but did not receive a response. Do you have an new email that we could resend it to, otherwise could you please check if the original email was received? Thank you.
