### ISSUE TITLE
Philips Clinical Science Germany

### ISSUE THREAD

**Issue by CStehning** [rrsg2020/data_submission#13]
Contact: Christian Stehning (christian.stehning@philips.com)

We plan to submit data acquired at 4 sites (with 1-3 data sets each, acquired on different MR systems).

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by CStehning** [comment]
We've collected data from 3 sites (1-3 MR scanners each). I'll send a link to the data drive to rrsg.challenge@gmail.com shortly. Please note that we are expecting data from 2 more sites in week 11 (March 9-13). Thank you very much for the organization!

On behalf of the Philips Clinical Science Germany ISMRM Challenge Team
Mariya Doneva
Burkhard Maedler
Kilian Weiss
Shuo Zhang
Christian Stehning

**Comment by mathieuboudreau** [comment]
Hi @CStehning !

Thank you - this is excellent !!

I just briefly looked at your submission, could you clarify two things to me?

1- Would it be possible for you to share the serial number of your phantom? You left that field as xxxx. If for some reason thats not possible, then could you at least share if the serial number is less than or greater than 0042? The reason being that phantoms produced with serial numbers 0042 and above have different T1 values than those below that serial number, so it'll be more fair to compare datasets that have the same reference values.

2- I see you included nifti files of fitted T1 maps in your submission. Could you clarify how you fit them? Did you use the pipeline demo I shared, the NIST software, or another piece of code?

Thanks!

Mathieu

**Comment by CStehning** [comment]
Dear Mathieu,
thanks for your note! Sorry for the missing phantom serial number - I realized too late that it is needed and the phantom was already shipped to a different site. 

1. I will send the serial number as soon as possible (next week, or the week after that at latest), and I'll also complete the yaml - files (we've used the same phantom at all sites).

2. The T1 maps in the NIFTI folder were created using the Jupyter demo notebook. I did both, a magnitude- and complex fit. The results look very similar to me. I'll leave it up to you which format you prefer (I have uploaded magnitude, real- and imaginary data).

Kind regards,
Christian

**Comment by mathieuboudreau** [comment]
Great, thanks for clarifying!

Yes, I agree that the magnitude and complex data fit comparatively well. Some of the organisers thought it would fit better, so this is something we hoped could be verified with the challenge.

No worries for the serial number - thanks!

I might ask a few follow up questions, but I'll start uploading the dataset and will update it as I get more information/data from you.

Best regards,

Mathieu

**Comment by CStehning** [comment]
Dear Mathieu, I've added the phantom serial number to the yaml files.

**Comment by CStehning** [comment]
Dear Mathieu, our data collection is complete. We've added data from two sites (Hamburg and Berlin). The data from Hamburg also include one in vivo data set. Have a good weekend!

**Comment by mathieuboudreau** [comment]
@CStehning great - thank you very much! Because you have submitted one of the largest datasets (if not the largest) for the challenge, it will take me a little bit of time to test and process it. I'll keep you posted.

**Comment by mathieuboudreau** [comment]
Hi @CStehning !

Thanks for submitting your datasets! I reviewed all of them, and they were all properly formatted - thank you for your attention to detail!

Your data was uploaded to the RRSG/qMRSG OSF.io repo: 

* NIST: https://osf.io/pwnc3/
* Human: https://osf.io/esu6t/

Here are screenshots of the Hamburg datasets (NIST and Human) to show that they fit well with the pipeline:

#  Hamburg - NIST

Pipeline output:

<img width="519" alt="Capture d’écran 2020-04-16 à 14 23 40" src="https://user-images.githubusercontent.com/1421029/79490077-e510fe80-7ff6-11ea-806a-5935af2c5903.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_13?filepath=data_submission%2Ft1_fitting_NIST.ipynb)

#  Hamburg - Human

Pipeline output:

<img width="519" alt="Capture d’écran 2020-04-16 à 14 23 03" src="https://user-images.githubusercontent.com/1421029/79490128-f823ce80-7ff6-11ea-93dc-489b14b9bba3.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_13?filepath=data_submission%2Ft1_fitting_Human.ipynb)

Thank you and your collaborators for your submission!
