### ISSUE TITLE
Ingham Institute, Australia 

### ISSUE THREAD

**Issue by mec640** [rrsg2020/data_submission#14]
**Name**: Madeline Carr, Robba Rai

**Number of datasets (sets of inversion recovery measurements**: (1)

Submission Checklist:

* [Y] Have you collected all the raw data exported directly from scanner into a single folder?
* [Y] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [Y] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by mec640** [comment]
Data ready for review.

**Comment by mathieuboudreau** [comment]
Hi @mec640,

Thank you for submitting a well-formatted dataset!

Your data was uploaded to the RRSG/qMRSG OSF.io repo: 

* NIST
  * https://osf.io/zjqk3/

* Human dataset
  * https://osf.io/j5pru/

I tested both of them in the demo processing pipeline, and they ran successfully.

# NIST

Pipeline output:

<img width="542" alt="Capture d’écran 2020-02-28 à 00 07 30" src="https://user-images.githubusercontent.com/1421029/75508987-9238a480-59c0-11ea-9207-651735d54ec4.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_14?filepath=data_submission%2Ft1_fitting_NIST.ipynb)

# Human

Pipeline output:

<img width="546" alt="Capture d’écran 2020-02-28 à 00 04 44" src="https://user-images.githubusercontent.com/1421029/75508996-995fb280-59c0-11ea-9488-b33f6f9927b5.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_14?filepath=data_submission%2Ft1_fitting_human.ipynb)

Thank you for your submission!

**Comment by mathieuboudreau** [comment]
Hi @mec640 !

Do you know what's the serial number of the phantom you used? The reason why this information is needed is because the T1 values of serial numbers above or equal to 0042 are different from those for serial numbers below 0042.

Thanks!

Mathieu

**Comment by mec640** [comment]
Hi @mathieuboudreau 

Sorry for the delay. The serial number is 0111 (>0042). Hope this helps in time!

Madeline

**Comment by mathieuboudreau** [comment]
Great - thank you @mec640 !

Hope all is well with you. I'll close this issue now - thank you for your submission!
