### ISSUE TITLE
Data Philips@MUHC

### ISSUE THREAD

**Issue by GuillaumeGilbert** [rrsg2020/data_submission#15]
**Name**: Guillaume Gilbert

**Number of datasets (sets of inversion recovery measurements)**: 2

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by mathieuboudreau** [comment]
Hi @GuillaumeGilbert

Thank you for submitting a well-formatted dataset!

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/qnhjt/

I tested both your magnitude and complex datasets in the demo processing pipeline, and they processed well:

# Magnitude dataset

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 02 13 14" src="https://user-images.githubusercontent.com/1421029/76137917-d2310480-601c-11ea-8fac-31a88c7162a7.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_15?filepath=data_submission%2Ft1_fitting_Mag.ipynb)

# Complex dataset

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 02 14 20" src="https://user-images.githubusercontent.com/1421029/76137926-e4ab3e00-601c-11ea-83c3-e3d6157ed9b8.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_15?filepath=data_submission%2Ft1_fitting_Complex.ipynb)

Thank you for your submission!

**Comment by mathieuboudreau** [comment]
@GuillaumeGilbert one minor question that I was wondering if you could clarify: are the two datasets (magnitude and real/imaginary) two separate measurements, or two different exports "modes" from the same measurement?

**Comment by GuillaumeGilbert** [comment]
It is a single measurement. The idea was to allow you to see if complex fitting works better than magnitude fitting.
Best regards,
Guillaume

**Comment by mathieuboudreau** [comment]
@GuillaumeGilbert Great - thanks for the clarification! I added a note to the data repository on OSF.io.
