### ISSUE TITLE
Montreal General Hospital - MRI Research Facility

### ISSUE THREAD

**Issue by alexensworth** [rrsg2020/data_submission#16]
**Name**: McGill MRI Methods Group

**Number of datasets (sets of inversion recovery measurements)**: 2 (1 in vivo, 1 phantom)

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by alexensworth** [comment]
Our data is ready for review.

**Comment by mathieuboudreau** [comment]
Hi @alexensworth @iveslevesque !

Thanks for submitting your datasets! Per our email discussion, this dataset is properly formatted and ready to be uploaded to OSF..

Your data was uploaded to the RRSG/qMRSG OSF.io repo: 

* NIST: https://osf.io/vtjpb/
* Human: https://osf.io/fxky2/

Here are screenshots of the NIST and Human datasets to show that they fit well with the pipeline:

#  NIST

Pipeline output:

<img width="516" alt="Capture d’écran 2020-05-01 à 15 01 29" src="https://user-images.githubusercontent.com/1421029/80826739-4f13d100-8bbd-11ea-82cc-2e8080aacf9a.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_16?filepath=data_submission%2Ft1_fitting_NIST.ipynb)

#  Human

Pipeline output:

<img width="516" alt="Capture d’écran 2020-05-01 à 15 01 15" src="https://user-images.githubusercontent.com/1421029/80826765-589d3900-8bbd-11ea-8543-dc849b381409.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_16?filepath=data_submission%2Ft1_fitting_Human.ipynb)

Thank you for your submission!
