### ISSUE TITLE
McGill University Health Centre - Cedars Cancer Centre

### ISSUE THREAD

**Issue by alexensworth** [rrsg2020/data_submission#17]
**Name**: McGill MRI Methods Group

**Number of datasets (sets of inversion recovery measurements)**: 3 (1 in vivo, 2 phantom)

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by alexensworth** [comment]
Our data is ready for review.

**Comment by mathieuboudreau** [comment]
Hi @alexensworth @iveslevesque !

Thanks for submitting your datasets! Per our email discussion, this dataset is properly formatted and ready to be uploaded to OSF..

Your data was uploaded to the RRSG/qMRSG OSF.io repo: 

* NIST: https://osf.io/yhvgf/
* Human: https://osf.io/btvd7/

Here are screenshots of the NIST (both with a power error, and without a power error) and Human datasets to show that they fit well with the pipeline:

#  NIST - Power Error

Pipeline output:

<img width="520" alt="Capture d’écran 2020-05-01 à 22 11 17" src="https://user-images.githubusercontent.com/1421029/80850841-b7cc6f00-8bf8-11ea-8b28-b70aae781365.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_17?filepath=data_submission%2Ft1_fitting_NIST_PowerError.ipynb)

#  NIST - No Power Error

Pipeline output:

<img width="520" alt="Capture d’écran 2020-05-01 à 22 10 36" src="https://user-images.githubusercontent.com/1421029/80850829-9a97a080-8bf8-11ea-80bd-1804fff3295a.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_17?filepath=data_submission%2Ft1_fitting_NIST_NoPowerError.ipynb)

#  Human

Pipeline output:

<img width="520" alt="Capture d’écran 2020-05-01 à 22 09 31" src="https://user-images.githubusercontent.com/1421029/80850810-763bc400-8bf8-11ea-9367-bcada5b6240d.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_17?filepath=data_submission%2Ft1_fitting_Human.ipynb)

Thank you for your submission!
