### ISSUE TITLE
0.35T-ISMRM/NIST Phantom Data

### ISSUE THREAD

**Issue by niloufarz** [rrsg2020/data_submission#24]
**Name**: (INSERT_NAME)

**Number of datasets (sets of inversion recovery measurements**: (INSERT NUMBER)

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by niloufarz** [comment]
[0.35T ISMRM_NIST Phantom Data.zip](https://github.com/rrsg2020/data_submission/files/4271295/0.35T.ISMRM_NIST.Phantom.Data.zip)

**Comment by mathieuboudreau** [comment]
Hi @niloufarz,

Do you know what's the serial number of the phantom you used? The reason why this information is needed is because the T1 values of serial numbers above or equal to 0042 are different from those for serial numbers below 0042 for your phantom version (130).

Thanks!

Mathieu

**Comment by mathieuboudreau** [comment]
Hi @siyuanhu1997 

Thanks for submitting your dataset! To make it match the recommended protocol, I divided your data into two datasets: a 4 point one (TI = 50, 500, 1000, 2500 ms) and 14 point one (all acquired TIs). Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/3frwb/

#  4 point dataset (TI = 50, 500, 1000, 2500 ms)

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-06 à 15 58 07" src="https://user-images.githubusercontent.com/1421029/76120055-3dea8180-5fcb-11ea-83b6-f59a02792773.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_24?filepath=data_submission%2Ft1_fitting_4point.ipynb)

# 14 point dataset

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-06 à 16 08 57" src="https://user-images.githubusercontent.com/1421029/76120050-3aef9100-5fcb-11ea-8387-7f9fd29f1deb.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_24?filepath=data_submission%2Ft1_fitting_14point.ipynb)

The only thing missing from your submission to be complete is the serial number of your phantom, for the reason described above.

# To do

* [x] Provide serial number of NIST phantom

**Comment by mathieuboudreau** [comment]
Thank you for emailing me the serial number @niloufarz ! I've updated the information in the dataset and re-uploaded it to OSF. 

Thank you for your submission!

**Comment by niloufarz** [comment]
Thanks Mathieu for working on our data.  T1 map looks awesome. 
Sorry for my late response, I was out of town.
