### ISSUE TITLE
University of Californa, Los Angeles

### ISSUE THREAD

**Issue by ngmaforo** [rrsg2020/data_submission#26]
**Name**: Nyasha G. Maforo - UCLA

**Number of datasets (sets of inversion recovery measurements**:  2

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

**Comment by mathieuboudreau** [comment]
Hi @ngmaforo!

Thanks for submitting your dataset! When I initially tested your dataset, the results were wildly off, as can be seen in these T1 maps:

<img width="524" alt="Capture d’écran 2020-03-06 à 23 49 17" src="https://user-images.githubusercontent.com/1421029/76136416-b5d89c00-600b-11ea-9edb-c4afb4aa54b4.png">

By looking at the curves of the fit, I suspected either that the conversion from DICOM to NII was not done correctly, or an error was made during the step of merging the data into a single file (with TI in the "time dimension") - maybe the TIs weren't in the right order.

I took your raw data, converted it to nifti with `dcm2niix`, and then merged the TI images, and the results were much better as can be seen bellow.

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/jkf69/

I tested your data with the demo fitting pipeline, at it fit correctly.

#  Skyra (no FS)

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 00 33 47" src="https://user-images.githubusercontent.com/1421029/76136453-339ca780-600c-11ea-9e5b-e008e9adcf1d.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_26?filepath=data_submission%2Ft1_fitting_Skyra.ipynb)

#  Prisma (no FS)

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 00 33 51" src="https://user-images.githubusercontent.com/1421029/76136451-2da6c680-600c-11ea-82bd-33debc92ae57.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_26?filepath=data_submission%2Ft1_fitting_Prisma.ipynb)

Thank you for your submission!
