### ISSUE TITLE
UNAM

### ISSUE THREAD

**Issue by lconcha** [rrsg2020/data_submission#5]
**Name**: Luis Concha

**Number of datasets (sets of inversion recovery measurements**: TBD

Data will be ready by the end of February.

**Comment by lconcha** [comment]
**Name**: Luis Concha, Erick Pasaye, Melissa Bass, Alonso Ramírez-Manzanares, Arturo Gozález
**Institutions**: Universidad Nacional Autónoma de México (LC, EP, MB), Centro de Investigación en Matemáticas (ARM), Universidad de Guanajuato (AG).

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

Data is ready, an email with a link has been sent to the organizers.

**Comment by mathieuboudreau** [comment]
Hi @lconcha,

Thank you for your submission!

While I was testing out your datasets, I noticed that while the GE data fit well, all the Philips data produced T1 maps that were way off (WM = 200ms, GM = 5000ms). See below for an example,

<img width="524" alt="Capture d’écran 2020-03-07 à 23 37 58" src="https://user-images.githubusercontent.com/1421029/76156009-a1110c80-60ce-11ea-861a-ac762b9f12af.png">

Luckily, @GuillaumeGilbert recently informed me that some older dicom to nifti converters don't handle the scaling factor correctly provided by some scanners (which needs to be done for quantitative MRI), as opposed to newer tools (see: [dcm2niix](https://github.com/rordenlab/dcm2niix)). I tried re-converting your Philips datasets using `dcm2niix`, and this resolved the fitting issue, as seen below,

<img width="524" alt="Capture d’écran 2020-03-07 à 23 38 11" src="https://user-images.githubusercontent.com/1421029/76156040-1da3eb00-60cf-11ea-95b3-7d5d96a4e4a4.png">

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/fubq6/

I tested one GE and one Philips dataset with the demo processing pipeline, and they ran successfully.

# GE

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 23 38 23" src="https://user-images.githubusercontent.com/1421029/76155995-69a26000-60ce-11ea-84db-658a4340c169.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_05?filepath=data_submission%2Ft1_fitting_GE.ipynb)

# Human

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-07 à 23 38 11" src="https://user-images.githubusercontent.com/1421029/76155993-6313e880-60ce-11ea-98c4-c4f275783a48.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_05?filepath=data_submission%2Ft1_fitting_Philips.ipynb)

# To do

* [ ] Upload data from re-scan of subjects at a later date (as authors indicated they are intending to do).

**Comment by mathieuboudreau** [comment]
Hi @lconcha - did you ever end up doing the rescan that you considered doing? If not, can I assume that you'll be unable to complete the rescan now in the near future and complete your submission by closing this issue?

**Comment by lconcha** [comment]
Hello @mathieuboudreau 

Sorry, covid19 got in the way of finishing further data collection. Given the outlook, it is unlikely that we can provide rescan data in the next two months, so feel free to close this issue.

If you feel that it would still be very useful in the future, after life returns to normal, I'd be more than happy to rescan the subjects. Let me know.

Best of luck.

**Comment by mathieuboudreau** [comment]
No worries - that's what I thought! 

I think we'll always be open to include additional data, so we'd be happy to include additional data when life returns to normal. I'll re-open then if needed.

Hope all is well with you.

Thanks !
