### ISSUE TITLE
Submission Sahlgrenska 

### ISSUE THREAD

**Issue by oscarjalnefjord** [rrsg2020/data_submission#6]
**Name**: Oscar Jalnefjord

**Number of datasets (sets of inversion recovery measurements**: 1

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by oscarjalnefjord** [comment]
The data is almost ready for review, I just have a few questions:
1. What defines "version" under "sample" in the yaml file? Is it serial number <0042 vs. >0041 or something else?
2. What should be put into the field "name" under "sequence" in the yaml file? (I run a Philips scanner)
3. (just a minor note) I went for complex data (real/imag) and used dcm2niix followed by fslsplit and fslmerge to get the corresponding nifti files. When I inspected the final nifti files in fsleyes I noticed that the real and imaginary data had different slice position. I guess it wont be an issue? The origin of this is that dcm2niix put the real/imag data in the 3rd dimension as only a single slice was scanned.

**Comment by mathieuboudreau** [comment]
>What defines "version" under "sample" in the yaml file? Is it serial number <0042 vs. >0041 or something else?

@agahkarakuzu You're the one who told me that the NIST phantom had different "versions". Do you know if this tracked somewhere, or how users could find out which one they're using? 

>What should be put into the field "name" under "sequence" in the yaml file? (I run a Philips scanner)

I don't think this is super important, it's just to gather more information about what folks did. When I converted my DICOMS to nifti (acquired on Siemens), the exported json file accompanying the header information of the DICOM has a parameter called "ScanningSequence" (see below), and that's what I placed there. I'll either clarify this point in the template, or omit it, after I see a few more submissions. (This is also partly why I encourage folks to upload their raw data as well)

<img width="571" alt="Capture d’écran 2020-02-18 à 12 17 20" src="https://user-images.githubusercontent.com/1421029/74752197-e2896700-5248-11ea-8636-448d91de31fd.png">


>(just a minor note) I went for complex data (real/imag) and used dcm2niix followed by fslsplit and fslmerge to get the corresponding nifti files. When I inspected the final nifti files in fsleyes I noticed that the real and imaginary data had different slice position. I guess it wont be an issue? The origin of this is that dcm2niix put the real/imag data in the 3rd dimension as only a single slice was scanned.

Interesting - I didn't know that! I think it should still be fine, what do you think @agahkarakuzu ? Once you share your data, I'll be able to test it a bit more to know.

Thanks!

**Comment by agahkarakuzu** [comment]
_Reference values are going to be different for different versions._

There are two **prototype** versions I know, `Phannie` and `Phreddie`, you can see the reference [here](https://collaborate.nist.gov/mriphantoms/bin/view/MriPhantoms/PhantomRoundRobinSchedule). [The data archive](https://collaborate.nist.gov/mriphantoms/bin/view/MriPhantoms/DataArchive) has examples for both. Commercialized versions of these phantoms were sold by HPD, now QualibreMD. 

If any center has one of these prototypes, version should refer to `Phannie` or `Phreddie`. If not, `serial number` seems relevant, see the description below: 

![image](https://user-images.githubusercontent.com/9632322/74753497-38a4dd00-523e-11ea-8596-78cd8d7dc1d7.png)

You can download **the latest** specs from [here](https://app.box.com/s/sqeuvq6uqbgx8ixa6mcp37nbrcpndwwm).

Bottomline, if people have a prototype phantom, the version is `Phannie` or `Phreddie`. If have the commercial one, then the serial number. The spec that comes with the commercial phantom contain the details.

**Comment by mathieuboudreau** [comment]
Great, thanks Agah. Which version do we have? We should add this to an FAQ page/section on this repo.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau the serial number is written on the `Plate 5` (which is the plate of the T1 array). Our phantom is from HPD. For the SN, I will check one of the highres images I acquired before and see if it is visible on the image.

**Comment by agahkarakuzu** [comment]
I could not find the serial number on my laptop, it is probably on my workstation at MHI. I have the page for reference values here: 

![image](https://user-images.githubusercontent.com/9632322/74758067-d3a0b580-5244-11ea-95cc-7fa649208870.png)

**Comment by oscarjalnefjord** [comment]
Thanks for the clarifications

The data is available for review now (emailed link)

**Comment by mathieuboudreau** [comment]
Hi @oscarjalnefjord ,

Your submission was properly formatted, thank you for your attention to detail! I did a few minor adjustments, because the template changed slightly today.

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/pg74t/

I tested it in the processing pipeline, and it ran successfully.

**Pipeline output:**

<img width="536" alt="Capture d’écran 2020-02-20 à 16 49 43" src="https://user-images.githubusercontent.com/1421029/74987745-78262180-5416-11ea-9062-572a48845a21.png">

**Run it here:**

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_06?filepath=data_submission%2Ft1_fitting.ipynb)
